# Red-flag symptom mappings for respiratory conditions
# Maps ICD-10 codes to emergency symptoms that require immediate escalation

J45.9:  # Asthma
  red_flags:
    - severe_respiratory_distress
    - unable_to_speak_full_sentences
    - cyanosis
    - altered_mental_status
    - peak_flow_below_50_percent

J18.9:  # Pneumonia, unspecified organism
  red_flags:
    - confusion
    - altered_mental_status
    - rapid_breathing_over_30
    - oxygen_saturation_below_92
    - severe_chest_pain

J44.9:  # Chronic obstructive pulmonary disease, unspecified
  red_flags:
    - severe_breathlessness_at_rest
    - worsening_leg_swelling
    - new_confusion
    - drowsiness
    - respiratory_failure

J06.9:  # Acute upper respiratory infection, unspecified
  red_flags:
    - stridor
    - noisy_breathing_at_rest
    - inability_to_swallow
    - dehydration
    - high_fever_with_breathing_difficulty

J20.9:  # Acute bronchitis, unspecified
  red_flags:
    - high_fever_over_3_days
    - bloody_sputum
    - shortness_of_breath_at_rest
    - severe_chest_pain
    - wheezing_unresponsive_to_treatment

J81.0:  # Acute pulmonary edema
  red_flags:
    - sudden_severe_breathlessness
    - frothy_pink_sputum
    - chest_pain_with_sweating
    - rapid_heart_rate
    - severe_anxiety

J93.0:  # Spontaneous tension pneumothorax
  red_flags:
    - sudden_stabbing_chest_pain
    - rapid_collapse
    - fainting
    - asymmetrical_chest_movement
    - severe_breathing_difficulty

J15.9:  # Bacterial pneumonia, unspecified
  red_flags:
    - persistent_high_fever
    - confusion
    - lethargy
    - oxygen_saturation_below_92
    - severe_dehydration

J12.9:  # Viral pneumonia, unspecified
  red_flags:
    - rapid_breathing_over_30
    - difficulty_speaking_full_sentences
    - cyanosis
    - severe_fatigue
    - unresponsive_to_initial_treatment

J21.9:  # Acute bronchiolitis, unspecified
  red_flags:
    - apnea
    - pauses_in_breathing
    - poor_feeding
    - severe_dehydration
    - grunting
    - severe_chest_retractions
